title: <p align="center"> Shravan Yadav </p>
logo: /assets/img/Shravan_photo.JPG
description:
  <p align="center">
  <a href="Shravan_Yadav_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shravan-yadav/">LinkedIn</a> |
  <a href="https://github.com/simplyshravan">GitHub</a> |
  <a href="https://www.kaggle.com/simplyshravan">Kaggle</a>
  
  <br>   
  I'm currently working as Data Architect in Girl Effect Enterprise India.
  Having experience in Finannce, HealthCare and Social Sector.
  Having total 10 years of experience.
  <br>
  </p>
theme: jekyll-theme-minimal
