title: Minimal theme
logo: /assets/img/Shravan_photo.JPG
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shravan-yadav/">LinkedIn</a> |
  <a href="https://github.com/simplyshravan">GitHub</a>
  <a href="https://www.kaggle.com/simplyshravan">Kaggle</a>
  
  <br>   
  I'm currently working as Data Architect in Girl Effect Enterprise India.
  Have experience in Finannce, HealthCare and Social Sector.
  Previously worked in Dell International Services, Fidelity Investments and NTTData.
  Having total 10 years of experience.
  <br>
  </p>
theme: jekyll-theme-minimal
